Shellcheck cleanup

diff --git a/vipe b/vipe
--- a/vipe
+++ b/vipe
@@ -6,6 +6,7 @@
 # create temporary file
 tmpfile=$(mktemp --tmpdir vipe.pipe.XXXXX)
 # make sure the file is deleted on script exit
+# shellcheck disable=SC2064
 trap "rm -f $tmpfile" EXIT
 
 # cat stdin to the new temp file
@@ -15,8 +16,7 @@ cat > "$tmpfile"
 # "hit return" prompt after the echoed message.
 # Redirection from/to /dev/tty prevents problems regarding in/output not a
 # terminal
-vim -c 'set cmdheight=2|echohl WarningMsg| echo "Use :cq to exit with error code and suppress output"|echohl None|set cmdheight=1' "$tmpfile" </dev/tty >/dev/tty
-if [ $? != 0 ]; then
+if ! vim -c 'set cmdheight=2|echohl WarningMsg| echo "Use :cq to exit with error code and suppress output"|echohl None|set cmdheight=1' "$tmpfile" </dev/tty >/dev/tty; then
     # Vim exited with error code (most likely due to :cq)
     # -> don't print file and return error
     exit 1
